worker_processes 1;
worker_rlimit_nofile 8192;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/stderr error;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 15s;
    keepalive_requests 10000;

    upstream heindall_api {
        server api1:8080 max_fails=0;
        server api2:8080 max_fails=0;
        keepalive 128;
    }

    server {
        listen 9999 reuseport backlog=4096;
        server_name _;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_buffering off;
            proxy_request_buffering on;
            proxy_connect_timeout 2000ms;
            proxy_send_timeout 2000ms;
            proxy_read_timeout 2000ms;
            proxy_next_upstream off;
            proxy_pass http://heindall_api;
        }
    }
}
